export enum CampaignType {
  DONATION = 'DONATION',
  ZAKAT = 'ZAKAT',
  SADQAH = 'SADQAH',
  EMERGENCY_RELIEF = 'EMERGENCY_RELIEF',
  EDUCATION = 'EDUCATION',
  HEALTHCARE = 'HEALTHCARE',
  FOOD_DRIVE = 'FOOD_DRIVE',
  OTHER = 'OTHER',
}
